services:
  app:
    container_name: app
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node.modules
    ports:
     - 3001:3000
    command: npm run start:docker
    env_file:
     - .env
    networks:
     - webnet
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: consumoBD #${DB_NAME}
      MYSQL_ROOT_PASSWORD:  #${DB_PASSWORD}
    ports:
      - '3307: 3306' #${DB_PORT}
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
networks:
  webnet:
volumes:
  my-db: